const route = require('express')()
const adminDashboardController = require('../../controllers/adminController/adminController')

route.get("/getDashboardData", adminDashboardController.getDashboardData)
route.get("/getViewAdsData", adminDashboardController.getViewAdsData)
route.get("/getShortLinkData", adminDashboardController.getShortLinkData)
route.get("/adminLogout", adminDashboardController.adminLogout)
route.get("/getWithdrawalsData", adminDashboardController.getWithdrawalsData)
route.get("/getUserData", adminDashboardController.getUserData)
route.get("/getPrivacy_policyData", adminDashboardController.getPrivacy_policyData)
route.get("/getTerms_of_useData", adminDashboardController.getTerms_of_useData)
route.get("/getDmcaData", adminDashboardController.getDmcaData)
route.get("/getOfferWallData", adminDashboardController.getOfferWallData)
route.get("/getAllUsersData", adminDashboardController.getAllUsersData)

route.post("/adminLogin", adminDashboardController.adminLogin)
route.post("/post_newAnnouncement_data", adminDashboardController.post_newAnnouncement_data)
route.post("/post_newFaq_data", adminDashboardController.post_newFaq_data)
route.post("/post_withdrawalMethod_data", adminDashboardController.post_withdrawalMethod_data)
route.post("/post_viewAds_directLink_data", adminDashboardController.post_viewAds_directLink_data)
route.post("/post_ShortenLink_data", adminDashboardController.post_ShortenLink_data)
route.post("/postGift_code_data", adminDashboardController.postGift_code_data)
route.post("/postOfferWall", adminDashboardController.postOfferWall)
route.post("/post_newHomepage_data", adminDashboardController.post_newHomepage_data)
route.post("/sendMarkitingEmails", adminDashboardController.sendMarkitingEmails)

route.patch("/update_referral_data", adminDashboardController.update_referral_data)
route.patch("/patch_announcement_data", adminDashboardController.patch_announcement_data)
route.patch("/patch_faq_data", adminDashboardController.patch_faq_data)
route.patch("/patch_withdrawalMethod_data", adminDashboardController.patch_withdrawalMethod_data)
route.patch("/update_viewAds_data", adminDashboardController.update_viewAds_data)
route.patch("/patch_viewAds_directLink_data", adminDashboardController.patch_viewAds_directLink_data)
route.patch("/update_ShortLink_data", adminDashboardController.update_ShortLink_data)
route.patch("/patch_ShortenLink_data", adminDashboardController.patch_ShortenLink_data)
route.patch("/updateWithdrawalsData", adminDashboardController.updateWithdrawalsData)
route.patch("/update_withdrawal_instructions_data", adminDashboardController.update_withdrawal_instructions_data)
route.patch("/patch_privacy_policy_data", adminDashboardController.patch_privacy_policy_data)
route.patch("/patch_terms_of_use_data", adminDashboardController.patch_terms_of_use_data)
route.patch("/patch_dmca_data", adminDashboardController.patch_dmca_data)
route.patch("/patchOfferWallInstructions", adminDashboardController.patchOfferWallInstructions)
route.patch("/patchOfferWall", adminDashboardController.patchOfferWall)
route.patch("/patch_homepage_data", adminDashboardController.patch_homepage_data)
route.patch("/sendMarkitingEmailsPatch", adminDashboardController.sendMarkitingEmailsPatch)

route.delete("/delete_announcement_data", adminDashboardController.delete_announcement_data)
route.delete("/delete_faq_data", adminDashboardController.delete_faq_data)
route.delete("/delete_withdrawalMethod_data", adminDashboardController.delete_withdrawalMethod_data)
route.delete("/delete_viewAds_directLink_data", adminDashboardController.delete_viewAds_directLink_data)
route.delete("/delete_ShortenLink_data", adminDashboardController.delete_ShortenLink_data)
route.delete("/deleteOfferWall", adminDashboardController.deleteOfferWall)
route.delete("/delete_homepage_data", adminDashboardController.delete_homepage_data)
route.delete("/deleteUserData", adminDashboardController.deleteUserData)

module.exports = route